{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ include "cp-kafka-connect.name" . }}
    chart: {{ include "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- $base_template := . }}
  {{- if .Values.serviceAccount.annotations }}
  {{- range $k, $v :=  .Values.serviceAccount.annotations }}
  annotations:
    {{ $k -}}: {{ tpl $v $base_template}}
  {{- end }}
  {{- end }}
{{- end }}
